using System.ComponentModel.DataAnnotations;

namespace KoiCareSystem.CSDL
{
    public class HoCa
    {
        [Key]  // Marking the HoId as the primary key
        public int HoId { get; set; }  // Primary Key, this will be auto-generated by the database

        [Required]  // Ensuring the pond name is required
        [StringLength(100)]  // Limiting the pond name to 100 characters
        public string TenHo { get; set; }

        // Removed 'HinhAnh' as per the request

        [Range(0, double.MaxValue)]  // Ensuring the size is non-negative
        public decimal? KichThuoc { get; set; }

        [Range(0, double.MaxValue)]  // Ensuring the depth is non-negative
        public decimal? DoSau { get; set; }

        [Range(0, double.MaxValue)]  // Ensuring the volume is non-negative
        public decimal? TheTich { get; set; }

        [Range(0, int.MaxValue)]  // Ensuring the number of pipes is non-negative
        public int? SoLuongOngThoatNuoc { get; set; }

        [Range(0, double.MaxValue)]  // Ensuring the pump power is non-negative
        public decimal? CongSuatMayBom { get; set; }
    }
}
